import 'package:african_food_app/models/location.dart';
import 'package:african_food_app/models/foods.dart';
import 'package:flutter/material.dart';

const myLocations = [
  Location(
    'L1',
    'All African Recipes',
    'assets/Images/All africa.jpg'
  ),
  Location(
    'L2',
    'West African Recipes',
    'assets/Images/West Africa.jpg'
  ),
  Location(
    'L3',
    'East African Recipes',
    'assets/Images/East Africa.jpg'
  ),
  Location(
    'L4',
    'South African Recipes',
    'assets/Images/South Africa.jpg'
  ),
  Location(
    'L5',
    'North African Recipes',
    'assets/Images/North Africa.jpg'
  ),
];

const myFoods = [
  Foods(
    id: 'F1',
    title: 'Miyan Tuase',
    rating: 4.0,
    serving: 6,
    imageUrl: 'assets/Images/Miyan-Taushe.jpg',
    locations: ['L1', 'L2'],
    duration: '75 mins',
    ingredients: [
      '1.5 lbs goat meat chunks',
      '1.5 lbs pumpkin peeled and cut into chunks',
      '? cup palm oil',
      '? cup roasted peanuts',
      '7 plum/roma tomatoes',
      '2 large onion',
      '1 bell pepper',
      '4 scotch bonnet peppers',
      '10 oz chopped spinach (fresh or frozen)',
      '5 oz sorrel (substitute with spinach more, spinach when unavailable)',
      '? cup ground dry cray fish',
      '2 tbsp shrimp bouillon',
      'salt to taste',
    ],
    directions: [
      'Slice both onion and 2 scotch bonnet peppers, and set aside.',
      'On low- medium heat in a large stock pot, braise the goat meat with the sliced onions, scotch bonnet peppers, 1 tsp bullion and 1 tsp salt for 30 minutes or until the meat is tender.'
          'While the meat is braising, blend the tomatoes, bell pepper, 1 onion, and  two scotch bonnet peppers.',
      'Place the blended tomato mix in a pot and cook on medium heat until the sauce reduces down to a thick paste, you might need to reduce the heat to prevent the tomato paste from burning.'
          'Once the meat is tender and done braising, add in the pumpkin chunks and 2 cups of water into the pot with the braised meat. The water should just cover the pumpkin chunks and meat. At this stage, adjust the seasoning of the broth and water that the pumpkins. Cover and boil for 15 minutes or until the pumpkin is tender.',
      'While the pumpkin are cooking, grind the peanuts in a blender, food processor with a mortar an pestle until it forms a rough paste, and set aside.',
      'Once the pumpkins are tender, use the back of a spoon to smash the pumpkin chunks, add in the crushed peanuts, tomato paste, cray fish, and bullion and stir the stew. Cover and cook for 5 minutes on  low- medium heat.'
          'After the stew has cooked for 5 minutes, add in the palm oil, chopped spinach and chopped sorrel, and cook the stew covered for 10 minutes on low heat.'
          'After 10 minutes, taste the stew for seasoning and adjust the salt if necessary. Turn the heat off and allow the stew to sit for 5 minutes, then serve hot'
    ],
  ),
  Foods(
    id: 'F2',
    title: 'Efo Riro',
    rating: 4.5,
    serving: 7,
    imageUrl: 'assets/Images/Efo Riro.jpg',
    locations: ['F1', 'F2'],
    duration: '55 mins',
    ingredients: [
      '4 pounds of spinach chopped',
      '1 pound of cooked meat of choice, I used fried Tilapia',
      '1/2 pound of small fresh water shrimp',
      '2 roma tomatoes',
      '1 red bell pepper',
      '1 large red onion',
      '2 habanero peppers',
      '2 cloves of garlic',
      '1/4 cup palm oil/ annatto oil',
      '3 tbsp powdered dried shrimp',
      'Salt to taste',
    ],
    directions: [
      'Blend half of the red onion with the tomatoes, bell pepper, garlic, and hot pepper. Chop the other half of the red onion.',
      'In a deep sauce pan or stock pot, heat the oil and saute the onions over medium heat until its golden brown.',
      'Add the blended tomato mix, and allow to cook over medium heat for about 30 minutes. Stir occasionally to avoid the mix from burning.',
      'After 30 minutes, the sauce should be significantly reduced, at this point season it with powdered dry shrimp and salt to taste.',
      'If cooking with cooked red meat or chicken, add them to the sauce at this point. If using dried mushrooms, re-hydrate and them at this point as well.',
      'Add the fresh shrimp to the sauce, then add the spinach. At this stage, the spinach may look too much, but allow to sit in the pot for about 1 minute.',
      'Gently stir the stew and the spinach until the spinach is wilted till about half the its original volume.',
      'Adjust the seasoning with salt to taste if necessary. At this point I added the fried tilapia, stirred and served.',
      'This soup is best served warm and freshly cooked.',
    ],
  ),
  Foods(
    id: 'F3',
    title: 'Edikang Ikong Soup',
    rating: 4.5,
    serving: 9 ,
    imageUrl: 'assets/Images/Edikaikong.jpg' ,
    locations: ['L1', 'L2'] ,
    duration: '65 mins',
    ingredients: [
      '2 lbs Malabar Spinach aka Water leaf',
'2 lbs Pumpkin leaves (you may use ugwu if you have that available)',
'3 lbs Goat meat cut into large bite size cubes',
'? cup Cooked shelled Apple snails',
'1 lbs Smoked Shrimp',
'? cup Palm oil',
'2 Red onions',
'2 Scotch bonnet peppers',
'4 tbsp Ground smoked dried shrimp aka Crayfish',
'3 tsp Chicken bouillon',
'Salt to taste',
    ],
    directions: [
      'Slice both onions and scotch bonnet peppers, and set them aside.',
'On low- medium heat in a large stock pot, braise the goat meat with the one of the onions, scotch bonnet peppers, 1 tsp bullion and 1 tsp salt for 30 minutes or until the meat is tender.',
'Half way into braising the goat meat, add ? a cup of water and stir the meat to prevent in from burning. Keep the pot covered at all times during the braising process.',
'While the meat is braising, wash the Malabar spinach in cool water to get rid of sand and dirt. Pick off the tough stems, but save the tender stems and leaves. Chop and set aside.',
'Wash the pumpkin leaves in cool water to get rid of sand and dirt. Pick off the tough stems, but save the tender stems and leaves. Chop and set aside.',
'Once the meat is tender and is done braising. Set aside.',
'In a deep pot heat up the palm oil on medium heat (be careful not to over heat the oil on high heat) and sauté the other sliced onion for 10 minutes until it is starting to get caramelized.',
'Add in the snails and smoked shrimp, and continue to sauté for another 5 minutes.',
'Add in the braised goat meat and reserve the braising liquid for another recipe. It is a very flavorful stock, and be used for another dish.',
'Add in 2 teaspoons of bullion, crayfish, then add in the chopped water leaves and the pumpkin leaves. Stir and allow to stew uncovered on medium heat for 10 minutes.',
'After 10 minutes, taste the stew for seasoning and adjust the salt if necessary. Turn the heat off and allow the stew to sit for 5 minutes, then serve hot'

    ],
  ),
  Foods(
    id: 'F4',
    title: 'Chicken/Beef Stew',
    rating: 4.0,
    serving: 5,
    imageUrl: 'assets/Images/Beef stew.jpg.',
    locations: ['L1, L2'],
    duration: '60 mins',
    ingredients: [
      '1-2 pound stew beef , cut in small pieces',
'1/2 -1 cup oil (Canola, Vegetable or Corn), adjust as needed',
'1 medium yellow onion',
'4 roma tomatoes , they are less acidic',
'4 peeled garlic cloves',
'? cup chopped parsley',
'3-4 tablespoon celery leaves',
'? -1 scotch bonnet pepper , optional',
'1-2 basil leaves',
'1 teaspoon fresh thyme',
'1 canned tomatoes sauce, 14 ounce',
'? teaspoon curry powder',
'1 teaspoon white pepper',
' 1-2 tablespoon smoked paprika',
'1 tablespoon Maggie powder or beef bouillon powder',
'l-2 green onion, sliced',
'salt to taste,'
    ],
    directions: [
      'Boil beef with salt, pepper and some chopped onions in a medium pot until tender. It will take approximately 30 minutes or more, depending the cut of beef and how you like your beef cooked. I sometimes use the pressure cooker to shorten the process. Reserve the stock for later use.',
'Add 1 cup oil to the pot/pan and brown the beef for about 5-10 minutes. Remove and set aside.',
'In a blender, blend the onions, tomatoes, garlic, parsley, celery, thyme, basil  and scotch bonnet pepper',

'Gently pour the blend of puree ingredients, and tomatoes puree  in the saucepan, add curry powder, white pepper , smoked paprika and bouillon powder bring to a boil, reduce heat and simmer for about 30 minutes.',
'Then return browned  beef and simmer for another 10 to 15 minutes.',
'Stir the pot frequently to prevent the sauce from sticking to the pot, occasionally adding beef stock or water as needed to prevent burns',
'Finally, add green onions.', 
'Adjust seasonings, sauce consistency with water/stock and salt.',
'Serve warm with desired side dish'

    ],
  ),
  Foods(
    id: 'F5',
    title: 'Afang Soup',
    rating: 4.5,
    serving: 7,
    imageUrl: 'assets/Images/Afang.jpg',
    locations: ['L1', 'L2'],
    duration: '70 mins',
    ingredients: [
      '2 lbs Malabar Spinach aka Water leaf',
'57 g 2 oz dried Afang leaves (may be labeled Okazi/Eru in the African store)',
'3 lbs Goat meat cut into large bite size cubes',
'? cup of cooked shelled Apple snails',
'? cooked shelled Clams',
'? cup palm oil',
'2 Red onions',
'2 Scotch bonnet peppers substitute with habanero peppers',
'4 tbsp Ground smoked dried shrimp aka crayfish',
'3 tsp Chicken Bullion',
'2 tbsp cayenne pepper/ crushed red pepper flakes optional',
'Salt to taste',
    ],
    directions: [
      'Slice both onions and scotch bonnet peppers, and set them aside.',
'On low- medium heat in a large stock pot, braise the goat meat with the one of the onions, scotch bonnet peppers, 1 tsp bullion and 1 tsp salt for 30 minutes or until the meat is tender.',
'Half way into braising the goat meat, add ? a cup of water and stir the meat to prevent in from burning. Keep the pot covered at all times during the braising process.',
'While the meat is braising, wash your Malabar spinach in cool water to get rid of sand and dirt. Pick off the tough stems, but save the tender stems and leaves. Chop and set aside.',
'In a food processor, roughly grind the afang leaves just to break it up a little. Afang leaves are mostly sold in the market already shredded, but you can break it up a little more using a food processor/ mortar and pestle so the shreds are not as long.'
'Once the meat is tender and is done braising, set aside.'
'In a deep pot heat up the palm oil on medium heat (be careful not to over heat the oil on high heat) and sauté the other sliced onion for 10 minutes until it is starting to get caramelized.',
'Add in the snails and clams, and continue to sauté for another 5 minutes.',
'Add in the braise goat meat and reserve the braising liquid. It is a very flavorful stock, and will still be used.',
'Add in 2 teaspoons of bullion, crayfish, and if you are spice inclined, cayenne pepper, stir, then add in the chopped water leaf.',
'Just like regular spinach, the water leaf will look like a lot at first, but wilt down in a few minutes. once the water leaf starts to wilt, add in the Afang leaves and stir.',
'Add about 1 cup of the braising liquid to the stew, turn down the heat to low, and continue cooking with the pot covered for another 10 minutes.',
'After 10 minutes, taste the stew for seasoning and adjust the salt if necessary.',
'Turn the heat off and allow the stew to sit for 5 minutes, then serve hot,',
    ],
  ),
  Foods(
    id: 'F6',
    title: 'Ofada Stew',
    rating: 4.5,
    serving: 8,
    imageUrl: 'assets/Images/Ofada Stew.jpg',
    locations: ['L1', 'L2'],
    duration: '55 mins',
    ingredients: [
      '7 large bell peppers',
'3 scotch bonnet peppers',
'4 large red onions',
'2 lbs braised goat meat (braised with 1 red onion, 1 scotch bonnet pepper, 1 tsp salt and 1 tsp bouillon',
'80 grams cleaned smoked dried fish (about 0.17lbs)',
'20 grams smoked dried shrimp about (0.04 lbs)',
'? cup palm oil',
'2 tsps bouillon',
'salt to taste',
'1 tbsp Iru (fermented locust beans) (optional)'
    ],
    directions: [

    ],
  ),
  Foods(
    id: 'F7',
    title: 'Akara(Bean Cake)',
    rating: 4.5,
    serving: 7,
    imageUrl: 'assets/Images/Akara.jpg',
    locations: ['L1', 'L2'],
    duration: '60 mins',
    ingredients: [
      '1.5 cups black eyed peas',
'1/2 red onion',
'2 scotch bonnet/ habanero peppers',
'3 tsp vegetable bouillon',
'Salt to taste',
'Oil for deep frying',
    ],
    directions: [
      'First of all, start by skinning the beans. Simply soak the beans in water for 3 minutes.', 
      'After about 3 minutes, the skin of the beans should start wrinkling a little bit. Place the beans in a food processor, with some water, just enough to cover it. Pulse the food processor about 5-6 times to agitate the beans.', 
      'This process breaks the beans up and separates the skins off the beans. Be careful, some water might splash out of the processor while pulsing the beans.',
'Pour the skinned beans in a bowl. Rinse several times to separate the beans from the skins, draining the skins with the water with each rinse. The skins should come off easily because the skins are lighter and should float to the top.',
'Once the beans are clean, soak them in water for at least 4 hours or overnight.'
'After the beans have soaked, drain the water that they have been soaking in, and rinse the beans one more time.',
'Using a mortar and pestle or a food processor, grind the scotch bonnet peppers to a rough paste and set aside.',
'Blend the beans and the onions with 1/2 a cup of water until it is completely smooth.',
'The texture should be similar to that of a thick muffin batter.',
'Heat up oil for deep frying in a pan up to 375°F while preparing the batter.',
'Add the salt, bullion, and scotch bonnet peppers to the bean batter, mixing continuously for five minutes to in-cooperate air into the batter.',
'With a large spoon, drop the batter a spoonful at a time into the hot oil to fry.', 
'Fry for 3-5 minutes on each side until it is golden brown both sides, take out of the frying oil and place into a colander or on paper towels to drain.',
'Serve hot!',
    ]
  ),
  Foods(
    id: 'F8',
    title: 'Nigerian Beans Porridge',
    rating: 4.5,
    serving: 8,
    imageUrl: 'assets/Images/Nigerian Beans.jpg',
    locations: ['L1', 'L2'],
    duration: '70 mins',
    ingredients: [
      '4 cups Honey beans/ Nigerian brown beans/ Black eyed peas',
'? cup palm oil',
'4 Roma tomatoes',
'4 scotch bonnet peppers',
'1 Large red onion',
'1 Large bell pepper',
'5 tbsp Ground dried shrimp (aka cray fish) optional',
'3 tsp Shrimp bullion can be substituted with vegetable bullion if vegan',
'Salt to taste',
    ],
    directions: [
      'Rinse the beans and place in a deep pot with 7 cups of water.',
'Boil the beans on medium heat until it becomes soft, it could take about 40 mins. If you are using black eyed peas, it might take a little longer.',
'While the beans are boiling, blend the tomatoes, peppers, and onions and set aside',
'Once the beans are softened from boiling (do not drain the water), turn the heat down to low, the pour in the blended tomatoes into pot.',
'Allow the beans to cook for an additional 10 minutes with the tomatoes, then add in the crayfish, bullion and palm oil. Stir, and cook for another 10 minutes.',
'Season the beans with salt to your taste. Turn off the heat, and allow to sit for 5 minutes before serving',

'Notes',
'The beans tend to thicken once they cool. If you prefer your beans lighter, add a little more water an reheat.',
    ],
  ),
  Foods(
    id: 'F9',
    title: 'Peppered Snail',
    rating: 4.5,
    serving: 6,
    imageUrl: 'assets/Images/Peppered Snail.jpg',
    locations: ['L1', 'L2'],
    duration: '45 mins',
    ingredients: [
      '2 lbs Shelled jumbo snails',
'2 large Onions',
'2 Scotch bonnet peppers (you may use less depending on your spice tolerance)',
'1 Small bell pepper',
'3 Limes (may substitute with 2 lemons)',
'2 tbsp Shrimp powder',
'1 tsp Seafood bouillon powder',
'1 Bay leaf',
'? cup Oil'
    ],
    directions: [
      'In a bowl, pour hot water and the juice of the three limes over the snails to remove the slime covering the snails. Be sure to keep the leftover rind of the limes of lemons.',
'Once the hot water that the snails have sat in cools down (allow to sit for about 10 minutes), used the lime or lemon rings to rub against the snails to remove the slime. It should come off pretty easily. Rise the snails thoroughly in cool water.',
'Slice one of the onions, and one of the scotch bonnet peppers, and set aside.',
'In a pot, boil the snails with the sliced onions and scotch bonnet peppers, 1 tsp bouillon, 1 tsp salt, 1 bay leaf and 1 cup pf water on low heat for 30 minutes.',
'After 30 minutes of boiling, turn off the heat, and set the snails aside.',
'Slice the other onion, scotch bonnet, and bell pepper.',
'In a pan, heat up the oil on medium heat, and saute the sliced onions and peppers until it is translucent. Add in the snails, and continue to saute for another 15 minutes. Taste, and adjust seasoning if necessary.',
'Serve the peppered snails hot! With a side of extra chili and onions if desired',

'Side Note: Goes well with beer, lol',
    ],
  ),
  Foods(
    id: 'F10',
    title: 'Moi Moi',
    rating: 4.5,
    serving: 16,
    imageUrl: 'assets/Images/Moi Moi.jpg',
    locations: ['L1', 'L2'],
    duration: '50 mins',
    ingredients: [
      '1.5 cups of black eyed peas',
'1/2 large bell pepper',
'2 scotch bonnet/ habanero peppers',
'1/2 cup neutral unflavored oil',
'1/2 large onion I used a red onion',
'8 oz smoked de-boned fish broken into small pieces',
'3 tsp bouillon',
'3 tsp salt or salt to taste',
'1/4 to 1/2 cup hot boiling water',
'3-4 broad sheets of banana leaves',
    ],
    directions: [
      'To skin the beans, soak the beans in water for 3 minutes, after about 3 minutes, the skin of the beans should start wrinkling a little bit.',
'Place the beans in a food processor, with water, just enough to cover it, then pulse the food processor about 5- 6 times to agitate the beans. This process breaks the beans up and separates the skins from the beans. Watchout for splashing water!',
'Pour the skinned beans in a bowl. Rinse several times to wash off any loose skin, draining the skins with the water with each rinse. The skins should come off easily because the skins are lighter and should float easily to the top.',
'Once the beans are clean, soak them in water for at least 4 hours or over night.',
'After the beans have soaked, drain the water that they have been soaking in, and rinse the beans one more time.',
'Blend the beans with 1 cup of water, the bell pepper, scotch bonnet peppers, onions and bouillon.',
'Place the blended beans in a bowl, mix in the oil and salt thoroughly then thin out the mixture with the hot water until it resembles the texture of a light cake batter (you may need less than 1/2 a cup of hot water, just make sure the texture is like a light cake batter).',
'You can taste the mixture to adjust for salt (it is will not taste good at this point since the beans are raw but at this point you are just tasting for seasoning).',
'Prep the ramekins by brushing each one with oil on the inside like you would a cake pan.', 'Fill each ramekin with the mixture till it is about 3/4 full, and then top it with a piece of fish.',
'In a deep pot with a properly fitted pot cover, place a sheet of banana leaf, and pour boiling water into the pot till it is about 1 inch deep. Place the ramekins into the pot, on top of the banana leaves. The hot water should not be more than half way up the ramekin. Cover the ramekins with a sheet of banana leaf',
'Depending on how wide your pot is, you may need to layer the ramekins in the pot. To do that, simply place the additional ramekins over the second sheet of banana leaf that covered the first layer of ramekins, then cover that layer with another sheet of banana leaf.',
'Cover the pot, and allow it to steam on low heat for 50 minutes. After 50 minutes, check the the Moi moi. Just like a cake, a skewer inserted into the middle of it should come out clean.'
 'If it does not, allow it to steam for another 10 minutes.',
'Allow the Moi moi to sit for 5 minutes then serve warm in the ramekin or unmolded.',

    ],
  ),
  Foods(
    id: 'F11',
    title: 'East African Pilau With Chicken',
    rating: 4.0,
    serving: 7,
    imageUrl: 'assets/Images/Pilau12.jpg',
    locations: ['L1', 'L3'],
    duration: '35 mins',
    ingredients: [
      '2 pounds of chopped bone-in chicken',
'3 cups of long grain basmati rice',
'2 cups of coconut milk + 2 cups of water',
'4 tbsp vegetable oil',
'1 large red onion sliced',
'4 cloves of garlic crushed',
'10 green cardamon pods',
'8 cloves',
'1 tbsp cumin seeds',
'1 tsp black pepper corns',
'1 tsp coriander seeds',
'1 cinnamon stick',
'1 bouillon cube',
'Salt to taste'
    ],
    directions: [
      'Start by toasting the spices on a pan over a medium flame. Toast the cinnamon stick, cardamon pods, and cloves until fragrant (takes about 2-3 minutes), then toast the cumin seeds, black pepper corns, and coriander seeds on medium heat until fragrant (for 1-2 minutes).',
'With a mortar and pestle, or in a spice grinder, coarsely grind all the spices except the cinnamon stick, and set aside.',
'Heat the oil in a pot over medium heat, then add in the sliced red onions. Allow to cook until lightly brown, then add the chicken, crushed garlic, ground spiced, and bouillon cube.',
'Stir and allow the chicken to brown slightly. This should take about 5 minutes.',
'Once the chicken is browned, stir in the rice for another two minutes, then add the coconut milk and water.',
'At this stage, adjust the salt if necessary (I added an extra tsp or so of salt), and add the cinnamon stick.',
'Cover the pot, and allow the Pilau to cook on low heat for 20 minutes. To make sure the pot is extra airtight, I used foil to seal the pot first before putting the lid on the pot.',
'After 20 minutes, turn off the flame, and set the pot aside covered for 5 minutes. After 5 minutes, uncover the pot, fluff the rice, and serve.'
    ],
  ),
  Foods(
    id: 'F12',
    title: 'Kenyan Samosas',
    rating: 4.0,
    serving: 25,
    imageUrl: 'assets/Images/Sambusa-samosas.jpg',
    locations: ['L1', 'L3'],
    duration: '40 mins',
    ingredients: [
      '1 lb/ 16oz/ 454g ground lamb',
'1 cup fresh/frozen peas',
'2 large shallots/ 1 small onion',
'1 tsp coconut oil this is just to saute the shallots/ onions',
'1 habanero/ scotch bonnet pepper',
'1/2 tsp bullion',
'1/2 tsp garam masala',
'1/2 tsp curry powder',
'1/2 tsp ginger powder',
'Salt to taste',
'25 count 8inch square spring roll wrappers',
'2 tbs plain flour plus 1- 2 tsp water',
'Oil for frying',
    ],
    directions: [
      'To make the filling: On low heat in a pan, saute the shallots/ onions in the coconut oil until it is translucent.',
'Add in the garam masala, curry powder, ginger powder, and bullion into the sauteing onions and allow to toast lightly for 2- 3 minutes, stirring continuously.',
'Add in the ground lamb and continue to stir, turning up the heat to medium.',
'Once the meat is no longer pink, add in the peas and cook for 10 minutes.',
'Taste the meat and adjust the salt if necessary.',
'Allow the filling to cool completely',
'To assemble, simply cut the spring roll sheets in half to form rectangles, place about 1 tsp of the filling on the top of the dough, and follow the folding techniques above.',
'Seal the dough with the plain flour and water mixture as shown above.',
'In a pan or fryer heat up enough oil (to 350 degrees Fahrenheit) to fry the samosa triangles',
'Once the samosas are golden brown, take them out of the oil and drain.',
'Serve them warm.',
    ],
  ),
//   Foods(
//     id: 'F13',
//     title: 'Nigerian Sesame Seed Stew',
//     rating: 3.9,
//     serving: 5,
//     imageUrl: 'assets/Images/beniseed-soup.jpg',
//     locations: ['L1', 'L2'],
//     duration: '60 mins',
//     ingredients: [
//       '1 ? cups sesame seeds',
// '4 lbs seafood (2lbs crabs, 1lb shrimp, 1 lb clams',
// '? lb dried/ smoked seafood (I used dried smoked shrimp)',
// '2 cups chopped spinach',
// '2 cups seafood stock',
// '1 large onion (sliced)',
// '4 plum tomatoes',
// '2 scotch bonnet peppers (chopped)',
// '? cup palm oil',
// '3 tbsp ground crayfish',
// '3 tsp shrimp bullion',
// 'salt to taste'
//     ],
//     directions: [
//       'Rinse the sesame seeds in a fine mesh sieve and drain. Place the seeds in a shallow pan, and toast stirring consistently on medium heat for 10- 15 minutes or until the sesame seeds are toasty and fragrant.',
// 'Blend the tomatoes and set aside.',
// 'Allow the sesame seeds to cool completely, then  grind into a powder in a food processor or with a mortar and pestle. Once the sesame seeds are powdered. Stop grinding so that the sesame seeds do not turn into a paste.',
// 'In pot, saute the onions and scotch bonnet peppers on medium heat until for 5 minutes.',
// 'Add in the blended tomatoes and saute for another 15 minutes. The tomatoes should be reduced to a paste.',
// 'Turn the heat down to low, then add in the crayfish and shrimp bullion. Saute for another 5 minutes.',
// 'After 5 minutes, add in the stock, and continue cooking the stew covered on low heat for 10 minutes.',
// 'After 10 minutes, add in the seafood, stir and add in the smoked and dried shrimp. Cover and allow to cook on low heat for 15 minutes.',
// 'Begin adding in the ground sesame seeds. Stir, and into the stew, cover and allow to simmer for 15 minutes.',
// 'After 15 minutes, add in the chopped spinach, stir and adjust the seasoning to your taste.', 'Cover and simmer for 5 minutes.',
// 'Serve the stew with traditional fufu, or with rice.',
//     ],
//   ),
  Foods(
    id: 'F14',
    title: 'Fonio Grits and Shrimp',
    rating: 4.0,
    serving: 6,
    imageUrl: 'assets/Images/Fonio and Shrimp.jpg',
    locations: ['L1', 'L2'],
    duration: '60 mins',
    ingredients: [
      '1? cups Fonio (rinsed)',
'220 g Fresh Shrimp (deveined)',
'80 g Smoked dried fish (cleaned and de-boned)',
'30 g Smoked dried shrimp (cleaned)',
'6 tbsp Unsalted butter or Coconut oil',
'1 Red onion (chopped)',
'2 tsp Shrimp bouillon',
'1 tsp Red pepper flakes or Chili pepper',
'Salt to taste'
    ],
    directions: [
      'In a pot, saute the chopped red onions in 3 tbsp of butter or coconut oil on medium heat until it is translucent.',
'Add in the smoked dried shrimp, the smoked dried fish, and the red pepper flakes. Continue to season for another 5 minutes.',
'Add in the rinsed Fonio, 1? tsp shrimp bouillon and 4 cups of water. Mix the Fonio and the water, and taste the water for seasoning. Add salt to your taste at this point.', 
'Cover the pot and on low heat, allow the Fonio to cook covered for 30 minutes or until the Fonio grains are tender. You may add more water if necessary.',
'To cook the shrimp that go on top of the Fonio, season the fresh shrimp with ? tsp of shrimp bouillon, and ? tsp salt. Allow it to marinate for about 5 minutes.',
'In a pan, heat up 3 tbsp of butter or coconut oil and cook the seasoned shrimp on medium heat for 3 minutes on each side. Save the coconut oil or butter that is left in the pan after cooking the shrimp to drizzle on top of the Fonio.',
'Serve the Fonio warm once it is soft, and top with the cooked fresh shrimp.'
    ],
  ),
  Foods(
    id: 'F15',
    title: 'Nigerian Peanut Stew',
    rating: 4.0,
    serving: 8,
    imageUrl: 'assets/Images/Groundnut soup.jpg.jpg',
    locations: ['L1', 'L2'],
    duration: '120 mins',
    ingredients: [
      'Braised Meat',
'2.5 lbs stewing goat meat',
'1 red onion sliced',
'2 tsp Bouillon',
'1 tsp salt',
'Groundnut Soup/Peanut Stew',
'2 cups raw skinned peanuts',
'3 scotch bonnet or habanero peppers roughly chopped use less if you do not like spicy food',
'0.5 lbs chopped spinach about 5 cups chopped, about 2 cups frozen',
'2 tbsp West African dried shrimp powder aka crayfish',
'3 tbsp palm oil',
'Salt to taste',
    ],
    directions: [
      'In a stew pot, braise the goat meat over low- medium heat with the onions, bullion and salt for 30-35 minutes. If you are cooking goat meat from an older or male goat, you may need to cook the meat for longer for it to be tender.',
'Next, toast the peanuts in a pan, stirring continuously over low heat, till the nuts turn toasty in color. It should take about 15- 25 minutes depending on how hot the pan is.',
'Allow the nuts to cool completely before grinding.',
'In a blender, food processor, mortar and pestle, grind the peanuts into a rough powder. Be mindful not to blend into a butter (it really does not hurt if blended to a butter, this is just how I learned to do it).',
'Mix the braising the liquid from braising the goat meat and water (should make up about 3 cups of liquid) with the ground peanuts and scotch bonnet peppers in a pot making sure there are no peanut lumps. Bring this mixture to a gentle boil over low- medium heat for about 10 minutes, mixing continuously to prevent burning.',
'At this stage, you may add more or less water depending on the consistency you prepare. If you prefer a lighter soup, add more water. If you prefer a thicker soup add no more water. Note that as the stew continues to cook, it usually thickens up. It also thickens a little more once it cools down.',
'After 10 minutes, add in the palm oil, braised meat, crayfish, and cook for another 5 minutes.',
'Add in the chopped spinach and simmer for 5 minutes on low heat, stiring occasionally to prevent burning.',
'Take the stew off the heat and serve.',
'Notes',
'Your groundnut soup/peanut stew can be served with your choice of fufu or rice .'

    ],
  ),
  Foods(
    id: 'F16',
    title: 'Ghana Sugar Bread Rolls',
    rating: 4.5,
    serving: 6,
    imageUrl: 'assets/Images/Ghana Sugar Bread.jpg',
    locations:['L1', 'L2'] ,
    duration: '120 mins',
    ingredients: [
      '390 g 2 2/3 cups bread flour',
'1/2 cup of sugar',
'3/4 cup scalded flour',
'2 1/4 tsp 1 sachet active dry yeast',
'1 tsp salt',
'1/8 tsp ascorbic acid'
    ],
    directions: [
      'Fill a small bowl with 1 cup of warm water (between 105°F- 115°F), sprinkle one tsp of sugar in the warm water and the yeast. Whisk the mixture till dissolved and set aside for 10 minutes.',
'After 10 minutes, the yeast should be foamy and should have bubbled up; if this does not happen, then your yeast may be inactive.', 'Dump that batch and try again with new yeast.',
'In a mixing bowl, mix in the flour, sugar, salt and ascorbic acid. Add in the scalded flour and activated yeast. Knead the dough for 15 minutes. It should be smooth to touch after kneading and not sticky.',
'Place the dough in a bowl that has been greased lightly with vegetable oil, cover, and allow to rise in a warm place till it doubles in size (usually about 1 hour).',
'After the dough is doubled, tip it out of the bowl on a clean work surface, and knead for five minutes.',
'Preheat an oven to 350°F',
'Divide the dough into 6 even balls and place in a baking pan covered with plastic wrap and allow it to rise until it has doubled in size.',
'Bake the bread in the pre-heated oven for 30-35 minutes.',
'Finally, cool the baked bread for at least five minutes and serve.'
    ],
  ),
  Foods(
    id: 'F17',
    title: 'Thieboudienne',
    rating: 4.0,
    serving: 8,
    imageUrl: 'assets/Images/Thieboud.jpg',
    locations: ['L1', 'L2'],
    duration: '60 mins',
    ingredients: [
      'The Fish',
'A handful of parsley about a heaping cup',
'3 cloves of garlic',
'1 Scotch bonnet/ habanero pepper',
'1 tsp shrimp bouillon',
'1 tsp black pepper',
'1 tsp salt',
'2.5  lbs blue snapper fish preferably cut into fish steaks or any white fish of your choice',
'The Rice',
'2 cups of broken jasmine rice or regular jasmine rice soaking',
'1 sweet potato',
'1 purple eggplant',
'4 carrots I used orange purple and yellow carrots',
'1/2 a head of cabbage',
'2 bell peppers',
'3 scotch bonnet/ habanero peppers',
'For the sauce',
'1 cup vegetable oil',
'1 cup tomato paste',
'1 large onions sliced',
'3 cloves of garlic',
'2 scotch bonnet/ habanero peppers I used green scotch bonnets, the color does not really matter',
'3 tbsp shrimp bouillon',
'1 tsp black pepper',
'Salt to taste'

    ],
    directions: [
      'Marinating the Fish',
'With a mortar and pistol or in a food processor, grind the parsley, garlic, scotch bonnet, bullion black pepper and salt into a rough paste.',
'Poke two holes into the flesh of the fish and stuff them with the parsley mix.',
'Broil or Fry the fish until it is golden brown on each side, and set aside for the sauce.',
'How to Cook the Rice',
'In a mortar and with a pestle or in a food processor grind the scotch bonnet peppers and garlic into a rough paste).',
'Saute the sliced onions in the oil over medium heat until translucent.',
'Add in the tomato paste, and stir fry for 5 minutes. The tomato paste may start to brown a little.',
'Add in the ground garlic and scotch bonnet and stir fry for another 2 minutes.',
'Add in bullion, black pepper, and 8 cups of water. At this stage, taste the sauce for salt, and adjust to your preference.',
'Add in the tough vegetable first in to the sauce and cook until tender. In this case, add in the sweet potatoes, cook until tender and remove, then the carrots, cook until tender and remove.', 
'Continue adding in the vegetables until all the vegetables are cooked.',
'Set the cooked vegetables aside and then add in the fish and cook in the sauce for 2-5 minutes.',
'Once the fish has simmered in the sauce for 2-5 minutes, gently remove it from the sauce.',
'At this point, drain the rice that has been cooking and pour into the sauce. The sauce should just cover the rice. Adjust the amount of water at this stage if needed to make sure that the rice is just covered.',
'Cover the pot and simmer on low-medium heat for 15-20 minutes. You may seal the cover of the pot with foil to prevent steam from escaping.',
'At the 15 minute mark, check that the rice has absorbed the moisture and is soft. Cover and cook for another 5 minutes if it needs more time. If the water has dried up and the rice is still not soft, add in 4 tbsp of water, cover and allow to cook.',
'Serve hot with the vegetables and fish, and lime wedges'
    ],
  ),
  Foods(
    id: 'F18',
    title: 'Cameroun Poulet DG',
    rating: 4.0,
    serving: 5,
    imageUrl: 'assets/Images/Cameroonian Pou.jpg',
    locations: ['L1', 'L2'],
    duration: '50 mins',
    ingredients: [
      'The Chicken Marinade',
'2 heaping cups of cilantro',
'2 stalks of celery',
'1 scotch bonnet habanero pepper',
'3 shallots or half of a red onion',
'A thumb size nub of ginger',
'1 tsp chicken bullion',
'1 tsp salt',
'1 tsp white pepper.',
'Other Ingredients',
'1 ? lbs boneless skinless chicken thighs chopped into 1 inch cubes',
'3 unripe plantains',
'1 ripe plantain',
'? cup vegetable oil',
'2 carrots cut in to coins',
'? green bell pepper cut into strips',
'? yellow bell pepper cut into strips',
'? orange bell pepper cut into strips',
'8 Roma tomatoes',
'1 onion',
'Salt to taste',
    ],
    directions: [
      'Start by prepping the marinade for the chicken by blending the cilantro, celery, scotch bonnet/ habanero pepper, shallots, ginger, bullion, salt and white pepper.',
'Marinade the chicken in half of the marinade for at least 30 minutes.',
'While the chicken is marinading, peel and cut the plantains 1 cm thick rounds (resembling coins), and fry until golden brown on both sides. Be careful not to over fry the unripe plantains trying to match their color with the ripe plantains. Unripe plantains are usually darker when fried as they have more sugar.',
'Broil the chicken pieces in under a hot broiler until it is golden brown. There is no need to flip the pieces since they are small.',
'Blend the tomatoes and set aside.',
'In a pot, saute the onions on medium heat for 5 minutes until they become translucent. After 5 minutes, add in the blended tomatoes, and turn the heat up to high.',
'Cook the tomatoes, stirring occasionally to prevent it from burning till the tomatoes have reduced and become thick.',
'Add in the other half of the marinade saved from earlier and continue to cook the sauce down on low-medium heat for another 5 minutes.',
'Add in the carrots, cook for 5 minutes then add in the plantain, chicken and bell peppers cook for another 5 minutes, then it is ready!'

    ],
  ),
  Foods(
    id: 'F19',
    title: 'Senegalese Sombi',
    rating: 4.0,
    serving: 2,
    imageUrl: 'assets/Images/Sombi.jpg',
    locations: ['L1', 'L2'],
    duration: '20 mins',
    ingredients: [
      '1 cup medium grain rice',
'2 cups water',
'1 cup coconut milk',
'1 cup coconut cream',
'1/2 cup brown sugar',
'1/4 tsp salt',
'A handful of coconut chips optional'

    ],
    directions: [
      'In a pot, boil the rice with two cups of water, until it is soft.',
'In a separate saucepan, bring the coconut milk, coconut cream, and brown sugar to a gentle boil over low-medium heat. Stir continuously for 5 minutes until the sugar is dissolved completely.',
'Add the rice and salt and continue cooking and stirring for 5 minutes.',
'Chill in the refrigerator and serve with coconut chips on top of the pudding.',
'Notes',
'If you want to serve this recipe warm, replace the coconut cream with coconut milk, and add an additional cup of coconut milk. Serve straight from the pot warm.',

    ],
  ),
  Foods(
    id: 'F20',
    title: 'Kuku Paka',
    rating: 4.0,
    serving: 4,
    imageUrl: 'assets/Images/Kuku-paka.jpg',
    locations: ['L1', 'L3'],
    duration: '60 mins',
    ingredients: [
      '2 Onions medium size',
'3 cm Ginger or thumb size',
'3 cloves Garlic',
'1 Scotch bonnet',
'? can Chopped tomatoes or 2 beef tomatoes, chopped',
'1 teaspoon Coriander',
'1 tablespoon Mild curry powder',
'4 legs Chicken',
'2 tablespoons Oil',
'? can Coconut milk or 200ml',
'Salt to taste',
    ],
    directions: [
      'Blend one onion, ginger, garlic, scotch bonnet pepper, tomatoes, coriander powder and curry powder into a paste in a food processor.',
'Slash the chicken. Make around 3 slashes in which ever direction you prefer on each side.', 'Rub some salt all over the chicken and place in a bowl.',
'Pour the the blended paste over the chicken and mix thoroughly with your hands. Keep aside to marinate for 20 mins.',
'While the chicken is marinating; chop the remaining onion finely.',
'Heat the oil in a saucepan under medium heat.'
'Add the onions into the pan and cook until soft and translucent.',
'Remove the chicken pieces from the paste and add into the pan. Sear on each side to brown.'
'Add the left over paste into the pan, add the coconut milk and a little salt to taste.',
'Cover the pan. Allow sauce to cook and the flavors to develop. This should take around 20 mins but is dependent on whether you are using soft or hard chicken. Hard chicken will take longer to cook properly.',
'Remove from heat and serve with coriander garnish.'

    ],
  ),
  Foods(
    id: 'F21',
    title: 'South African Bobotie',
    rating: 4.0,
    serving: 6,
    imageUrl: 'assets/Images/Bobotie.jpeg',
    locations: ['L1', 'L4'],
    duration: '60 mins',
    ingredients: [
      '1 tablespoon oil, or as needed',
'1 onion, chopped',
'1 pound ground beef',
'? slice bread',
'? cup milk, divided',
'1 egg, beaten, divided',
'? cup seedless raisins',
'1 tablespoon white vinegar',
'2 teaspoons white sugar',
'1 teaspoon ground turmeric',
'1 teaspoon salt',
'? teaspoon curry powder',
'? teaspoon ground black pepper',
'2 bay leaves',
'1?? tablespoons chutney',

    ],
    directions: [

'Preheat oven to 350 degrees F (175 degrees C).',

'Heat oil in a skillet over medium-high heat; add onion and saute until browned, about 5 minutes. Add ground beef to onion and saute until browned, about 5 minutes.',

'Soak bread in 1/4 cup milk in a small bowl, mash, and add to ground beef mixture; stir in 1/2 of beaten egg, raisins, vinegar, sugar, turmeric, salt, curry powder, and ground black pepper.',

'Transfer beef mixture to glass baking dish; insert bay leaves.',

'Bake in preheated oven for 30 minutes. Whisk remaining 1/2 egg and remaining 1/4 cup milk together in a small bowl; pour over meat mixture and return to oven for 30 minutes.',

'Serve with chutney.',

    ],
  ),
  Foods(
    id: 'F22',
    title: 'Nigerian Jollof Rice',
    rating: 5.0,
    serving: 4,
    imageUrl: 'assets/Images/Jollof Rice.jpg',
    locations: ['L1', 'L2'],
    duration: '75 mins',
    ingredients: [
      '4 tbsp canola oil',
'1 tbsp butter',
'14.5 oz canned hunts tomato unsalted',
'2 red bell peppers',
'6 oz canned tomato paste',
'3 large whole red onion',
'1 cup chopped red onion',
'1/4 cup blended crayfish',
'4 Habanero peppers (based on how spicy you want)',
'4 1/2 cups long grain parboiled rice',
'2 cups chicken stock',
'1 tbsp Maggi or knorr cubes',
'1 tbsp salt',
'1/2 tsp cayenne pepper and black pepper',
'1/2 tsp white pepper',
'3 single bay leaves',
'1/2 tbsp curry powder',
'1/2 tsp garlic/onion powder',
'1/2 tsp thyme',
'1/4 tsp ginger'

    ],
    directions: [
      'Blend tomatoes, red bell peppers, habanero peppers, large red onions until consistency is smooth and set aside',
'Wash the rice thoroughly to rid off starch and set aside.',
'To a medium-sized pot on medium heat, heat canola oil and butter',
'Throw in chopped onions and allow to fry for about 5 mins or until redness starts to fade',
'Pour in tomato paste and allow to fry for about 10-15 minutes, stirring continuously to avoid burning.',
'Add in your blended mixture, crayfish, Maggi, cayenne & black pepper, white pepper, bay leaves, curry powder, garlic, thyme. Mix and fry for about 30 minutes, continuously stirring to avoid burning.',
'Add chicken stock and salt. Mix and allow cook for an additional 10 mins',
'Add in washed rice and a bit of water (if necessary), and reduce heat to low.',
'Cover pot with aluminum foil, to avoid heat from escaping through lid',
'Cook rice on low heat for about 30 mins',
'Once cooked, mix thoroughly to combine',
'Cover and let cook for an additional 10 mins.',

'To get the party Jollof flavor, turn up the heat and let the rice burn for about 3 mins. (Be careful with this step, so you do not burn the whole rice)',
'Notes',
'For spices: Add as much or as little depending on your preference and taste choice.'

    ],
  ),
  Foods(
    id: 'F23',
    title: 'North African Chermoula',
    rating: 3.0,
    serving: 6,
    imageUrl: 'assets/Images/Chermoula.png',
    locations: ['L1', 'L4'],
    duration: '80 mins',
    ingredients: [
      'North African Chermoula Sauce',
'15ml (1 Tbsp) olive oil',
'1 red onion, chopped',
'3 garlic gloves, grated',
'2cm fresh ginger, peeled and grated',
'7.5ml (1 ? tsp) cumin',
'10ml (2 tsp) smoked paprika',
'5ml (1 tsp) cinnamon',
'Zest of 1 orange',
'Zest of 1 lemon',
'2 x 400g tinned cherry tomatoes',
'250ml (1 cup) chicken or beef stock',
'125ml (1/2 cup) good quality red wine',
'1 can red kidney beans',
'Handful parsley, roughly chopped',
'Salt and pepper, to taste',

'Pork Chops:',
'6 pork loin chops',
'45ml (3 Tbsp) butter',
'15ml (3 Tbsp) olive oil',
'Rosemary, to taste'

    ],
    directions: [
      'North African Chermoula Sauce:',
'Heat a pan with a dash of olive oil and fry the onion, garlic and ginger until soft and translucent.',
'Add all the spices and fry for another minute until fragrant.',
'Add the citrus zest, cherry tomatoes, stock and wine.',
'Allow to cook on a low heat for about 45 minutes.',
'Add the red kidney beans, herbs and season to taste',
'Pork Chops:',
'Heat a pan with the butter and oil on a high heat. Fry the pork chops until golden for about 5 - 6 minutes per side and do not forget to render the fat to make it nice and crispy.',
'Place the pork chops in the sauce and allow to marinate until you are ready to serve.'
'Heat a pan and dry toast the spices for extra flavour.',
'Place the toasted spices, along with the rest of the ingredients, into a blender and blend until smooth. Adjust seasoning to taste.'

    ],
  ),
  Foods(
    id: 'F24',
    title: 'Shakshuka',
    rating: 3.5,
    serving: 6,
    imageUrl: 'assets/Images/Shakshuka.jpg',
    locations: ['L1', 'L5'],
    duration: '35 mins',
    ingredients: [
      '3 tablespoons oil',
'2 green peppers chopped',
'1 large onion chopped',
'3 cloves garlic minced',
'1? teaspoon paprika',
'? teaspoon cumin',
'? teaspoon red pepper flakes',
'28 ounces crushed tomatoes canned)',
'? cup tomato sauce',
'Salt and pepper to taste',
'6 large eggs',
'? cup fresh parsley or cilantro chopped'

    ],
    directions: [
      'In a large sauté pan, heat olive oil on medium heat. Add the chopped bell pepper and onion and cook until the onion becomes translucent – about 5 minutes.',
'Add the minced garlic, paprika, cumin, and red pepper flakes and cook for another 1 minute.',
'Stir in the crushed tomatoes and tomato sauce and bring to a simmer over medium heat for 5-7 minutes until it starts to thicken. Add salt and pepper to taste.',
'Make six wells in the sauce (one at a time) using a spoon and crack the eggs inside each well.',
'Cover and simmer for 5 to 8 minutes or until the yolks are set to your taste.',
'Garnish with parsley or cilantro. Enjoy!'

    ],
  ),
  Foods(
    id: 'F25',
    title: 'East African Chapati',
    rating: 3.9,
    serving: 7,
    imageUrl: 'assets/Images/Chapati.jpg',
    locations: ['L1', 'L3'],
    duration: '30 mins',
    ingredients: [
      '500 ml (2 cups) flour',
'250 ml (1 cup) wholewheat flour',
'10 ml (2 tsp) salt',
'45 ml (3 Tbsp) coconut oil, melted',
'310 ml (1 ? cup) water, lukewarm',

    ],
    directions: [
      'In a large mixing bowl, combine all the ingredients and mix until a dough starts to form. On a lightly floured surface, knead the dough for about 3-5 minutes or until smooth and elastic.',
'Cover the dough and allow to rest for about 30 minutes. (Poke the dough ith your finger, if it bounces back, it is ready)',
'Divide the dough into 6-8 smaller balls. Roll them out on a lightly floured surface to about 3 mm thick.',
'For the layering: Gently brush them with oil and roll them (like a scroll). Coil the dough (so it almost shapes like a coney bun), cover and allow to rise again for about 10 minutes.', 'Then roll the dough out on a lightly floured surface. (If you do not wish to layer the dough as much, you can skip this step.)',
'Fry on a medium heat for about 2-3 minutes per side or until cooked and golden.',

    ],
  ),
  Foods(
    id: 'F26',
    title: 'Matoke With Beans',
    rating: 4.0,
    serving: 2,
    imageUrl: 'assets/Images/Matoke.jpg',
    locations: ['L1', 'L3'],
    duration: '50 mins',
    ingredients: [
      '4 Green matoke',
'2 tablespoons Oil',
'1 Onion chopped',
'1 teaspoon Grated ginger',
'2 cloves Garlic chopped',
'? teaspoon Cumin',
'1 can Chopped tomatoes or 400g',
'? can Kidney beans or 200g, drained',
'? cup Vegetable stock or water',
'? teaspoon Chilli flakes',
'Salt to taste',
'? cup Coriander chopped'

    ],
    directions: [
      'Wash the bananas very well. Remove the tops and ends.',
'Boil in hot water for 10 mins, then remove from heat.',
'Allow to cool before removing the skin.'
'Heat oil in a saucepan.',
'Add onions to the pan and stir for a few minutes until the onions become translucent.',
'Add the cumin, garlic and ginger. Stir continuously for about 1 min, then add the chopped tomatoes and the beans.',
'Pour in the stock or water with a dash of salt. Add the chilli flakes and cover the pan.',
'Allow to simmer for about 10 mins.',
'Pour in the bananas.',
'Leave to simmer for additional 5 mins under low heat, then add the coriander.',
'Use a wooden spoon to slightly mash the content of the pot to the consistency you desire.',
'Remove from heat and serve.',

    ],
  ),
  Foods(
    id: 'F27',
    title: 'Chicken and Couscous',
    rating: 4.0,
    serving: 6,
    imageUrl: 'assets/Images/Chicken conscious.jpeg',
    locations: ['L1', 'L5'],
    duration: '35 mins',
    ingredients: [
      '2 cups water'
'1?? cups uncooked couscous'
'? cup golden raisins'
'? cup thawed orange juice concentrate, undiluted'
'? cup lemon juice',
'2 tablespoons water',
'2 tablespoons olive oil',
'2 teaspoons ground cumin',
'? teaspoon salt',
'? teaspoon black pepper',
'3 cups chopped ready-to-eat roasted skinned, boned chicken breasts (about 3 breasts)',
'2 cups chopped peeled cucumber',
'1 cup chopped red bell pepper',
'? cup thinly sliced green onions',
'? cup chopped fresh cilantro',
'Sliced green onions (optional)',

    ],
    directions: [
'Bring the water to a boil in a medium saucepan, and gradually stir in couscous and raisins. Remove from heat. Cover; let stand 5 minutes. Fluff with a fork.'
'Combine orange juice and next 6 ingredients (orange juice through black pepper); stir well with a whisk.'
'Combine the couscous mixture, juice mixture, chicken, and remaining ingredients in a large bowl, and toss well.' 
'Garnish with green onions, if desired.'

    ],
  ),
  Foods(
    id: 'F28',
    title: 'Beniseed Soup',
    rating: 3.8,
    serving: 8,
    imageUrl: 'assets/Images/beniseed-soup.jpg',
    locations: ['L1', 'L2'],
    duration: '70 mins',
    ingredients: [
      '1 ? cups sesame seeds',
'4 lbs seafood (2lbs crabs, 1lb shrimp, 1 lb clams',
'? lb dried/ smoked seafood (I used dried smoked shrimp)',
'2 cups chopped spinach',
'2 cups seafood stock',
'1 large onion (sliced)',
'4 plum tomatoes',
'2 scotch bonnet peppers (chopped)',
'? cup palm oil',
'3 tbsp ground crayfish',
'3 tsp shrimp bullion',
'salt to taste',

    ],
    directions: [
      'Rinse the sesame seeds in a fine mesh sieve and drain. Place the seeds in a shallow pan, and toast stirring consistently on medium heat for 10- 15 minutes or until the sesame seeds are toasty and fragrant.',
'Blend the tomatoes and set aside.',
'Allow the sesame seeds to cool completely, then  grind into a powder in a food processor or with a mortar and pestle.' 
'Once the sesame seeds are powdered. Stop grinding so that the sesame seeds do not turn into a paste.',
'In pot, saute the onions and scotch bonnet peppers on medium heat until for 5 minutes.',
'Add in the blended tomatoes and saute for another 15 minutes. The tomatoes should be reduced to a paste.',
'Turn the heat down to low, then add in the crayfish and shrimp bullion. Saute for another 5 minutes.',
'After 5 minutes, add in the stock, and continue cooking the stew covered on low heat for 10 minutes.',
'After 10 minutes, add in the seafood, stir and add in the smoked and dried shrimp. Cover and allow to cook on low heat for 15 minutes.',
'Begin adding in the ground sesame seeds. Stir, and into the stew, cover and allow to simmer for 15 minutes.',
'After 15 minutes, add in the chopped spinach, stir and adjust the seasoning to your taste.', 'Cover and simmer for 5 minutes.',
'Serve the stew with traditional fufu, or with rice.'

    ],
  ),
  Foods(
    id: 'F29',
    title: 'Potjiekos',
    rating: 3.9,
    serving: 6,
    imageUrl: 'assets/Images/Potjestkos.jpg',
    locations: ['L1', 'L4'],
    duration: '160 mins',
    ingredients: [
      '3-4 lbs oxtail',
'2 tsp kosher salt, more to taste',
'1 tsp black pepper, more to taste',
'2 tbsp ghee (or 1 tbsp butter + 1 tbsp olive oil)',
'1 medium onion, finely chopped (about 1 cup chopped)',
'2 cloves garlic, minced',
'1 tbsp tomato paste',
'3/4 cup medium-bodied red wine (South African pinot noir or Shiraz/Syrah preferred)',
'1 tsp ground coriander',
'1 tsp cumin',
'1 tsp paprika',
'1/4 tsp ground cinnamon',
'1/4 tsp ground nutmeg',
'2 pinches ground cloves',
'1/4 tsp ground cardamom (or 1 whole green cardamom pod)',
'1/2 tsp hickory liquid smoke (optional if cooking over an open fire)',
'1 bay leaf',
'1 cup chicken stock, more as needed',
'1 lb small yukon gold potatoes, cut into bite-sized chunks',
'2 carrots, cut into bite-sized chunks',
'1 zucchini, cut into bite sized chunks',
'3/4 lb brussels sprouts',
'1/2 head cauliflower (about 1 lb), broken into bite-sized pieces',
'1/2 lb white mushrooms, cut into bite sized chunks if needed',
'1/2 lb cherry or grape tomatoes',

    ],
    directions: [
      '1. Pat the oxtails dry using paper towels, then season all over with the salt and pepper. In a dutch oven or deep skillet, warm the ghee over medium heat. Add the oxtails and brown until dark and crisp at the edges, about 3 minutes per side, in batches if needed to prevent overcrowding. Remove the oxtails and set aside, then add the onion to the dutch oven; saute until softened, about 6 minutes. Add the garlic and tomato paste, and stir together until sizzling and aromatic, about 1 minute. Stir in the wine, coriander, cumin, paprika, cinnamon, nutmeg, cloves, cardamom, liquid smoke, and bay leaf; simmer to deglaze the pan, about 3 minutes, scraping up any cooked bits at the bottom of the dutch oven as you go.',
'2. Return the oxtails to the pot, then add enough chicken stock to reach about 3/4 of the way up the oxtails, about 1 cup. Bring to a simmer, then cover and reduce heat to low; simmer for 1 1/2 hours, stirring every once in a while to ensure the oxtails are well coated with the flavorful sauce.',
'3. After the oxtails have simmered for 1 1/2 hours, season the sauce with more salt and pepper to taste, then add the following vegetables in layers, in this order: potatoes, carrots, zucchini, brussels sprouts, and cauliflower. Cover and simmer for 30 minutes without stirring, then add the mushrooms and cherry tomatoes; simmer for another 30 minutes.',
'4. Gently stir the pot to lightly coat the the vegetables, then distribute into bowls and serve.'

    ],
  ),
  Foods(
    id: 'F30',
    title: 'Tahini-Beet Dip',
    rating: 4.0,
    serving: 2,
    imageUrl: 'assets/Images/Tahini.jpg',
    locations: ['L1', 'L5'],
    duration: '75 mins',
    ingredients: [
      '1 lb. beets, trimmed',
'1/2 cup tahini',
'3 tbsp. fresh lemon juice',
'2 garlic cloves',
'3 ice cubes',
'Kosher salt and freshly ground black pepper tbsp. Extra-virgin olive oil for garnish',
'1 tbsp. toasted pine nuts, for garnish',
'Egyptian flatbread or pita, for serving'

    ],
    directions: [
      'Bring a medium pot of water to a boil. Add the beets and cook until very tender, about 1 hour.',
'Drain and peel the beets, discarding the cooking liquid, then transfer to a blender along with the tahini, lemon juice, garlic, and ice cubes. Season with salt and pepper and puree until very smooth. Spoon into a shallow serving bowl, drizzle with olive oil, garnish with pine nuts, and serve with Egyptian flatbread or pita, for scooping.'

    ],
  ),
  Foods(
    id: 'F31',
    title: 'Tunisian Molokhia',
    rating: 4.0,
    serving: 6,
    imageUrl: 'assets/Images/Tunisia braised.jpg',
    locations: ['L1', 'L5'],
    duration: '180 mins',
    ingredients: [
      '3/4 oz. dried molokhia leaves',
'2/3 cup plus 1 Tbsp. olive oil',
'2/3 cup molokhia powder',
'1/4 cup tomato paste',
'2 tbsp. finely minced garlic (from 6 cloves)',
'2 tsp. harissa paste, plus more for serving if desired',
'1 tsp. ground coriander',
'1 tsp. ground caraway',
'Kosher salt',
'1/2 tsp. freshly ground black pepper',
'2 lb. boneless veal such as shoulder, shank, or another stewing or braising cut, cut into 2-inch pieces',
'Lemon wedges, for serving',
'Baguette or other crusty bread, for serving'

    ],
    directions: [
      'In a sieve or spice grinder, grind molokhia leaves into a powder, which should yield about ⅔ cup.',
'In a large saucepan, bring 8 cups of water to a low boil. Set a heatproof liquid measuring cup next to the stove.',
'In a large Dutch oven or heavy-bottomed pot over low heat, combine the oil and molokhia; let cook just until lightly bubbling and sizzling, then immediately and briskly whisk in about one cup of the boiling water. As soon as the water is completely incorporated, whisk in another cup. Raise the heat to medium and whisk in the remaining hot water; bring to a simmer, then reduce the heat to medium-low, cover and cook, stirring every 20 minutes to prevent the bottom from burning, until the mixture has turned a dark, nearly black green, 2 to 2 ½ hours.',
'Whisk in the tomato paste, garlic, harissa, coriander, caraway, a generous pinch of salt, and the pepper. Add the veal, then raise the heat to medium-high to bring the mixture back up to a simmer. Once simmering, reduce back down to medium-low, then continue cooking, uncovered, stirring every 15-20 minutes until the meat is tender, and the sauce has thickened and reduced by about two thirds, 1 ¾ to 2 hours.',
'Taste and adjust the seasoning as needed. Ladle into bowls and serve with lemon wedges for squeezing, more harissa if desired, and crusty bread.',

    ],
  ),
  Foods(
    id: 'F32',
    title: 'Bunny Chow',
    rating: 4.0,
    serving: 4,
    imageUrl: 'assets/Images/Bunny Chow.jpg',
    locations: ['L1', 'L4'],
    duration: '55 mins',
    ingredients: [
      '1 pound chicken thighs or breast cut in bite-sized pieces',
'1/2 cup canola or cooking oil',
'2-3 Curry leaves',
'1 teaspoons minced ginger',
'2 teaspoons minced garlic',
'1 Tablespoon curry powder or more',
'1 medium onion diced',
'2 medium tomatoes diced',
'1 cinnamon stick',
'1 1/2 teaspoon paprika',
'3 green cardamom pods lightly crushed',
'8 ounce or less potatoes cleaned and cut into cubes',
'1 15 ounce can chickpeas rinsed and drained',
'½ teaspoon cayenne pepper optional',
'11/2 cup or more chicken broth or water',
'Salt and pepper to taste'

    ],
    directions: [
      'When ready to cook, heat up large Sauce- pan with oil, and add onions, garlic,ginger, cinnamon stick, curry leaves, cardamom pods and curry powder, stir occasionally for about 2-3 minutes until onions is translucent.',
'Add tomatoes followed by chicken, stir and sauté for about 2-3 more minutes. Add chicken stock/ water if necessary to prevent any burns'
'Next add chickpeas, potatoes and chicken broth , about 1 1 1/2 cup , add more as needed.',
'Bring to a boil and let it simmer until sauce thickens, it might take about 25 minutes or more.',

    ],
  ),
  Foods(
    id: 'F33',
    title: 'Cape Malay Chicken Curry',
    rating: 4.0,
    serving: 4,
    imageUrl: 'assets/Images/Cape Malay.jpg',
    locations: ['L1', 'L4'],
    duration: '70 mins',
    ingredients: [
      '4 tbsp oil',
'1 medium onion, finely chopped',
'2 tbsp ginger, finely chopped',
'1 tsp chili flakes, or fresh hot peppers to taste',
'1 1/2 tsp coriander seeds',
'2 tsp fennel, ground, or 4 tsp whole fennel seeds',
'1 1/2 tsp ground cumin',
'1 tsp turmeric',
'1/2-1 tsp black pepper, coarsely ground',
'15 cardamom pods, whole pods',
'1/2 tsp cinnamon',
'1 tbsp garam masala',
'14 oz can crushed tomatoes , or diced tomatoes',
'1 1/2 lb chicken pieces',
'2 tsp garlic, finely chopped',
'2 tsp brown sugar',
'1 tbsp lemon juice',
'2 -3 tsp salt'
    ],
    directions: [
      'Put the 7 spices — from the coriander seeds down to the garam masala — in a mortar and pestle. Pound them together so the cardamom pods burst and the whole thing becomes a mess of spices. Discard the skin of cardamom pods. Continue to pound the spices until they become like a powder.',
'Heat the oil in a pot, add the onion and ginger over fairly high heat, and stir occasionally for a few minutes. Add the chili flakes and spices and stir for 2 minutes. You might need to add more oil (Spices slurp up oil as they fry)',
'Add the can of crushed tomatoes and stir. Cook until everything bubbles up together.'
'Add the chicken pieces, and stir to coat well, keeping heat high until everything is bubbling away. Turn the heat down, put on a lid, and simmer for about 20 minutes.',
'Add the garlic, sugar, lemon juice and salt to the curry. Cover with lid but leave a small opening for a steam to escape; simmer for 15 minutes or longer. Taste the sauce, and adjust seasoning according to your taste.',

'Near the end of cooking, skim off extra oil/fat with a spoon, as it collects in corners of the pot, if needed. Serve the curry warm with rice.'

    ],
  ),
  Foods(
    id: 'F34',
    title: 'Sukuma Wiki',
    rating: 4.0,
    serving: 4,
    imageUrl: 'assets/Images/Sukuma.jpg',
    locations: ['L1', 'L3'],
    duration: '30 mins',
    ingredients: [
      '1 bunch collard greens about 6 cups chopped.',
'1 lb beef cooked (optional)',
'2 tbsp olive oil',
'1 onion',
'2 tomatoes diced',
'½ tsp cayenne pepper',
'½ tsp bouillon powder',
'1 tsp salt',
'1 tsp black pepper'

    ],
    directions: [
      'Saute onions in olive oil on medium heat.',
'Add chopped tomatoes and stir for about 2 minutes.',
'Add cayenne pepper, bouillon, salt, and black pepper.',
'If using beef, add it and stir.',
'Cook for 5-10 minutes on low heat.'
'Add chopped collard greens.',
'Stir and cook for 3-5 minutes or until your preferred crunchy level.',
'Serve with cauliflower rice or low carb fufu!'

    ],
  ),
  Foods(
    id: 'F35',
    title: 'Makai Paka',
    rating: 4.1,
    serving: 3,
    imageUrl: 'assets/Images/Makai paka.webp',
    locations: ['L1','L3'],
    duration: '25 mins',
    ingredients: [
      '3 ears corn, shucked',
'1 tablespoon unsalted butter',
'1 medium tomato, diced',
'1 serrano chile, minced',
'1 teaspoon ground coriander',
'1 teaspoon green chile',
'½ teaspoon ground turmeric',
'27 oz coconut milk(800 mL)',
'2 tablespoons lemon juice',
'1 bunch fresh cilantro, chopped'
    ],
    directions: [
      'Blanch the corn in a large pot of boiling water for 3 minutes. Remove the corn from the pot.',
'Let the corn cool slightly, then slice crosswise into 2-inch (5 cm) pieces, about 4 per cob.',
'In a medium pot, melt the butter over medium heat. Add the tomato and cook until softened.', 'Add the serrano chili, ground coriander, green chile powder, and turmeric and stir well.',
'Add the coconut milk and bring to a simmer.', 'Add the corn and lemon juice and stir well.',
'Transfer the corn and sauce to a serving bowl and garnish with cilantro.'

    ],
  ),
  Foods(
    id: 'F36',
    title: 'Yekik Alicha',
    rating: 3.9,
    serving: 4,
    imageUrl: 'assets/Images/Yekik Alicha.webp',
    locations: ['L1', 'L3'],
    duration: '80 mins',
    ingredients: [
      '3 tablespoons cooking oil',
'2 cups split red or green peas',
'2 medium red onions chopped',
'3 cups water',
'1 tablespoon ginger and garlic paste',
'salt',
'1 tablespoon black pepper',
'3 green jalapeno pepper sliced, or green', 'Anaheim'

    ],
    directions: [
      'Wash the peas and boil in water over medium heat until tender. Drain the water from it and set aside.',
'Put the oil in a pot and heat up. Add the sliced onions and sauté until it becomes tender and golden brown.',
'Then, add the peas to the pot continuously for 3 minutes. Prevent it from sticking to the bottom of the pot by stirring frequently.',
'Add the garlic and ginger paste, pepper, and salt to taste.',
'Cook for 25 minutes on low heat. Stir occasionally.',
'Add the green chili, stir, and cook for further 3 minutes.',
    ],
  ),
];
